version: "3"

vars:
  gobin: go
  ldflags: "-extldflags '-static' -w -s -buildid="
  gcflags: "all=-trimpath={{.PWD}} -dwarf=false -l"
  asmflags: "all=-trimpath={{.PWD}}"
  bin: "{{.PWD}}/bin"
  app: "gox"
  app_bin: "{{.bin}}/{{.app}}"
  remote_user: root
  remote_host: 192.168.200.53
  remote_dir: "~/"

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  GOOS: linux

tasks:
  setup:
    desc: set up
    silent: true
    cmds:
      - mkdir -p {{.bin}}

  build:
    desc: common build
    deps: [setup]
    silent: false
    cmds:
      - >
        {{.gobin}} build
        -tags netgo
        -ldflags="{{.ldflags}}" 
        -trimpath 
        -gcflags="{{.gcflags}}" 
        -asmflags="{{.asmflags}}" 
        -o {{.app_bin}} cmd/server/main.go
      - strip {{.app_bin}}
      - objcopy --strip-unneeded {{.app_bin}}

  in-docker-build:
    deps: [build]
    silent: false
    cmds:
      - mv {{.app_bin}} /build/bin

  docker.build:
    desc: build bin via docker
    deps: [setup]
    silent: false
    cmds:
      - docker compose -f docker-compose.build.yaml up --build --force-recreate

  docker.gox:
    desc: build prod docker image
    deps: [docker.build]
    silent: false
    cmds:
      - docker build -f Dockerfile -t ghcr.io/devil666face/gox:latest .
      - |
        docker save ghcr.io/devil666face/gox:latest | gzip > gox.tar.gz

  docker.push:
    desc: push docker in registry
    deps: [docker.gox]
    silent: true
    cmds:
      - docker push ghcr.io/devil666face/gox:latest
