version: "3"

dotenv: [".env.build"]

vars:
  gobin: go
  ldflags: "-X 'main.Username=$BUILD_USERNAME' -X 'main.Password=$BUILD_PASSWORD' -extldflags '-static' -w -s -buildid="
  gcflags: "all=-trimpath={{.PWD}} -dwarf=false -l"
  asmflags: "all=-trimpath={{.PWD}}"
  bin: "{{.PWD}}/bin"
  app: "gox"
  app_bin: "{{.bin}}/{{.app}}"
  remote_user: root
  remote_host: 192.168.200.53
  remote_dir: "~/"
  subject_alt_name: "IP:127.0.0.1, IP:192.168.0.1, DNS:proxy.local.lan"

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  GOOS: linux

tasks:
  setup:
    desc: set up
    silent: true
    cmds:
      - mkdir -p {{.bin}}

  build:
    desc: common build
    deps: [setup]
    silent: false
    cmds:
      - >
        {{.gobin}} build
        -tags netgo
        -ldflags="{{.ldflags}}" 
        -trimpath 
        -gcflags="{{.gcflags}}" 
        -asmflags="{{.asmflags}}" 
        -o {{.app_bin}} cmd/gox/main.go
      - strip {{.app_bin}}
      - objcopy --strip-unneeded {{.app_bin}}

  build.garble:
    desc: common build
    deps: [setup]
    silent: false
    vars:
      gobin: garble
      app_bin: "{{.bin}}/{{.app}}_garble"
      gcflags: "all=-trimpath={{.PWD}} -dwarf=false"
    cmds:
      - >
        {{.gobin}} -literals -tiny build 
        -tags netgo
        -ldflags="{{.ldflags}}" 
        -trimpath 
        -gcflags="{{.gcflags}}" 
        -asmflags="{{.asmflags}}" 
        -o {{.app_bin}} cmd/gox/main.go
      - strip {{.app_bin}}
      - objcopy --strip-unneeded {{.app_bin}}

  in-docker-build:
    deps:
      - build
      - build.garble
    silent: false
    cmds:
      - cp {{.app_bin}} {{.app_bin}}_crypt && bincrypter {{.app_bin}}_crypt
      - cp {{.app_bin}}_garble {{.app_bin}}_garble_crypt && bincrypter {{.app_bin}}_garble_crypt
      - upx --best --ultra-brute {{.app_bin}} -o {{.app_bin}}_upx
      - upx --best --ultra-brute {{.app_bin}}_garble -o {{.app_bin}}_garble_upx
      - mv {{.app_bin}}* /build/bin

  docker.build:
    desc: build bin via docker
    deps: [setup]
    silent: false
    cmds:
      - docker compose -f docker-compose.build.yaml up --build --force-recreate

  gox:
    desc: build prod docker image
    deps: [docker.build]
    silent: false
    cmds:
      - docker build -f Dockerfile -t ghcr.io/devil666face/gox:latest .
      - |
        docker save ghcr.io/devil666face/gox:latest | gzip > gox.tar.gz

  push:
    desc: push docker in registry
    deps: [docker.gox]
    silent: true
    cmds:
      - docker push ghcr.io/devil666face/gox:latest

  web.certs:
    desc: "generate certs for web"
    cmds:
      - openssl genrsa -out ca.key 2048
      - openssl req -x509 -new -nodes -key ca.key -sha256 -days 3650 -out ca.crt -subj "/CN=GoxCA"
      - echo "subjectAltName = {{.subject_alt_name}}" > extfile.cnf
      - |
        for name in server; do \
          openssl genrsa -out $name.key 2048; \
          openssl req -new -key $name.key -out $name.csr -subj "/CN=$name"; \
          openssl x509 -req -in $name.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out $name.crt -days 3650 -sha256 -extfile extfile.cnf; \
        done
      - cp server.key server.crt cmd/gox/
      - rm -f *.csr *.cnf

  ping:
    desc: ping all hosts
    dir: ansible
    vars:
      bin: .venv/bin/
    cmds:
      - uv sync
      - "{{.bin}}ansible all -m ping"

  playbook:
    desc: run playbook
    dir: ansible
    vars:
      bin: .venv/bin/
    cmds:
      - "{{.bin}}ansible-playbook playbook.yml -vvv | tee ansible.log"
